#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$app = new Application('Custom Builder', '1.0');

$app->add(new CreateBlockCommand);

$app->run();
